### ISSUE TITLE
config needs to be bound to the host

### ISSUE THREAD

**Issue by JAP42** [ALinuxNinja/docker-postal#12]
The postal.yml file needs to be bound to the host or you can not get the configurations to save properly. Including domains which revert back to postal.example.com. 

Unfortunatlly, when trying to add `./data/config:/opt/postal/config` to the volumes, the container will no longer start because of missing directories. Non of the sub directories seem to create if its mapped.

**Comment by eveandcats** [comment]
That is because the postal codebase includes files in the 'config' folder.

To customize your configuration, you can copy the postal configuration out:
`docker cp postal:/opt/postal/config/postal.yml postal.yml`
and then edit docker-compose.yml to mount the modified postal.yml to /opt/postal/config/postal.yml

You can also modify postal.yml.j2 in the 'src' folder, and build the docker container manually which will modify the template used for the file.

**Comment by JAP42** [comment]
Sorry, I forgot to get back to this. Just a suggestion, the template should include a hostname variable to replace all of the example.com with a hostname set in docker compose. No need to build the image again, simply modify the J2 template and add the variable to the compose.
